### ISSUE TITLE
Incorect header parsing if an ascii is present

### ISSUE THREAD

**Issue by neodc** [aeshirey/EmlParser#14]
Hello,

If the eml headers contain any not ascii character the parsing shift, for example this code:

```rust
use eml_parser::parser::EmlParser;

fn main() {
    let result = EmlParser::from_string("Foo: tést\nBar: bar\n\nHello".to_string())
        .ignore_body()
        .parse();
    
    dbg!(result);
}
```

Will have this output:

```
[src/main.rs:8] result = Ok(
    Eml {
        headers: [
            HeaderField {
                name: "Foo",
                value: Unstructured(
                    "tés",
                ),
            },
            HeaderField {
                name: "\nBa",
                value: Unstructured(
                    " ba",
                ),
            },
        ],
        from: None,
        to: None,
        subject: None,
        body: None,
    },
)
```

If the character is the last one of the header value it can even panic:

```rust
use eml_parser::parser::EmlParser;

fn main() {
    let result = EmlParser::from_string("Foo: testé\nBar: bar\n\nHello".to_string())
        .ignore_body()
        .parse();
    
    dbg!(result);
}
```

```
thread 'main' panicked at 'byte index 10 is not a char boundary; it is inside 'é' (bytes 9..11) of `Foo: testé
Bar: bar

Hello`', /home/neodc/.cargo/registry/src/github.com-1ecc6299db9ec823/eml-parser-0.1.2/src/parser.rs:429:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::str::slice_error_fail
   3: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/str/traits.rs:214:21
   4: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/str/traits.rs:64:9
   5: <alloc::string::String as core::ops::index::Index<core::ops::range::Range<usize>>>::index
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/string.rs:2224:10
   6: eml_parser::parser::EmlParser::read_field_body
             at /home/neodc/.cargo/registry/src/github.com-1ecc6299db9ec823/eml-parser-0.1.2/src/parser.rs:429:27
   7: eml_parser::parser::EmlParser::read_raw_header_field
             at /home/neodc/.cargo/registry/src/github.com-1ecc6299db9ec823/eml-parser-0.1.2/src/parser.rs:240:32
   8: eml_parser::parser::EmlParser::parse_header_fields
             at /home/neodc/.cargo/registry/src/github.com-1ecc6299db9ec823/eml-parser-0.1.2/src/parser.rs:127:46
   9: eml_parser::parser::EmlParser::parse_email
             at /home/neodc/.cargo/registry/src/github.com-1ecc6299db9ec823/eml-parser-0.1.2/src/parser.rs:101:23
  10: eml_parser::parser::EmlParser::parse
             at /home/neodc/.cargo/registry/src/github.com-1ecc6299db9ec823/eml-parser-0.1.2/src/parser.rs:92:19
  11: test_eml::main
             at ./src/main.rs:4:18
  12: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
```

I think the problem is in EmlParser::read_field_body (and maybe other), when it currently add 1 to the position I think it should add the current character [len_utf8](https://doc.rust-lang.org/std/primitive.char.html#method.len_utf8) and not 1.

**Comment by aeshirey** [comment]
Using `len_utf8` does indeed appear to resolve the problem. I've pushed code and included some tests that show it should now work. Merci pour votre aide !

I will push the new version to crates.io probably tomorrow..

**Comment by aeshirey** [comment]
[Version 0.1.3 now on crates.io](https://crates.io/crates/eml-parser/0.1.3)
